/* TryHackMe-style task structure, one entry per stage.
   Each task: t=title, d=diff(1-5), w=what you do, q=sub-questions with revealable answers,
   r=indices into that stage's res[] array, p=points                     */
const TASKS={
"M0.1":[
 {t:"Why networking comes first",d:1,w:"Read the mission argument before touching a tool. Understand that every attack travels over a network you must be able to read.",
  q:[{q:"Why can you not do security without networking?",a:"Because you cannot detect, trace or explain an attack that you cannot see happening on the wire."}],
  r:[0],p:10},
 {t:"OSI vs TCP-IP",d:2,w:"Learn both models and map real protocols onto each. Interviewers ask this constantly.",
  q:[{q:"Which OSI layer does DNS sit in?",a:"Layer 7, application. In TCP-IP it is part of the application layer."},
     {q:"Which layer does a switch operate at?",a:"Layer 2, data link."},
     {q:"Which layer does a router operate at?",a:"Layer 3, network."}],
  r:[1],p:20},
 {t:"Read a packet capture",d:3,w:"Open Wireshark and identify TCP, UDP, DNS and HTTP without help. This is a tested skill.",
  q:[{q:"Which filter shows only DNS traffic?",a:"udp.port 53  (or port 53 for TCP)"},
     {q:"Which filter shows failed HTTP responses?",a:"http.response.code >= 400"}],
  r:[3,4],p:30},
 {t:"Subnet by hand",d:4,w:"Split a /24, then a /16, on paper. If you cannot do this in your head Wireshark is just noise.",
  q:[{q:"How many usable hosts in a /24?",a:"254, because .0 and .255 are reserved."},
     {q:"How many usable hosts in a /26?",a:"62, because 2^(32-26) = 64 minus 2."}],
  r:[2],p:40},
 {t:"Build your first topology",d:4,w:"Install Packet Tracer, build a three-router network, verify the routing table.",
  q:[{q:"What command shows the routing table?",a:"show ip route"}],
  r:[5],p:40}
],
"M0.2":[
 {t:"Survive the terminal",d:1,w:"Get comfortable moving around, reading files and finding your way without a mouse.",
  q:[{q:"What command shows the current directory?",a:"pwd"},
     {q:"What command lists files including hidden ones?",a:"ls -la"}],
  r:[2],p:10},
 {t:"Bandit levels 0 to 10",d:2,w:"Do these in order. Skipping levels is why people get stuck at level 20 later.",
  q:[{q:"Why do the levels matter even if the challenges get silly?",a:"They build the reflexes you use later when a real incident is not a puzzle."}],
  r:[0],p:30},
 {t:"Users, services and permissions",d:3,w:"Learn to add a user, manage a service and understand why permissions go wrong.",
  q:[{q:"What command adds a user on Ubuntu?",a:"sudo useradd -m username  (then sudo passwd username)"},
     {q:"What does chmod 750 mean?",a:"Owner gets rwx, group gets r-x, others get nothing."}],
  r:[1,3],p:40},
 {t:"Logs and evidence",d:3,w:"Know where logs live and how to read them. This is the bridge to SOC work.",
  q:[{q:"Where do Linux system logs live?",a:"/var/log, with auth logs for SSH and sudo."},
     {q:"What command shows the last 20 lines of a file?",a:"tail -n 20 /path/to/file"}],
  r:[1],p:40},
 {t:"Missing Semester toolkit",d:4,w:"Work through the MIT lectures on shell, scripting and debugging. Best free lecture series going.",
  q:[{q:"Name one tool from the course you have never used.",a:"Any valid answer, as long as you can say what it does."}],
  r:[4],p:50}
],
"M0.3":[
 {t:"Python fundamentals",d:2,w:"Lists, dicts, loops, functions, file reading. Enough to write a real tool, nothing more.",
  q:[{q:"Which Python method reads an entire file?",a:"f.read()  (or iterating the file object line by line)"},
     {q:"How do you write a list to a JSON file?",a:"json.dump(data, f)"}],
  r:[1,2],p:20},
 {t:"Parse a log and flag anomalies",d:3,w:"Build a script that reads a log file and counts failed logins by source IP. Your first real detection.",
  q:[{q:"Why count by source IP rather than total count?",a:"One host attacking 500 times matters more than 500 hosts attacking once."}],
  r:[0,2],p:40},
 {t:"Automate a boring task",d:3,w:"Take a repetitive manual chore and script it. Measure the time you save.",
  q:[{q:"What is the point of writing this script?",a:"Removing repeatable manual work so you can spend attention on the alerts that actually matter."}],
  r:[0],p:30},
 {t:"Use MITRE ATT&CK in Python",d:4,w:"Pull technique data programmatically. This is how detection engineering starts.",
  q:[{q:"What is ATT&CK useful for on defence?",a:"Mapping your detections to real attacker techniques so you know what coverage you lack."}],
  r:[3],p:40},
 {t:"Ship it",d:3,w:"Add a README, a test and a screenshot to one of your existing tools.",
  q:[{q:"What goes at the top of a security tool README?",a:"The threat it addresses, then how to run it, then a safe demo."}],
  r:[4],p:40}
],
"M1.1":[
 {t:"CIA, AAA and the basics",d:1,w:"Confidentiality, integrity, availability, plus authentication, authorisation and accounting.",
  q:[{q:"Which CIA property does encryption protect?",a:"Confidentiality."},
     {q:"Which does a hash protect?",a:"Integrity."}],
  r:[0],p:10},
 {t:"Risk language",d:3,w:"Turn a vague worry into a written risk register you could hand a manager.",
  q:[{q:"What four things make up a risk statement?",a:"Asset, threat, vulnerability, and the business impact if it happens."},
     {q:"Difference between risk and vulnerability?",a:"A vulnerability is the weakness. Risk is the likelihood and impact of it being exploited."}],
  r:[0],p:30},
 {t:"Map controls to NIST CSF 2.0",d:3,w:"The six functions are Govern, Identify, Protect, Detect, Respond, Recover. Place real controls under each.",
  q:[{q:"Which function does a SIEM sit under?",a:"Detect."},
     {q:"Which function does a backup strategy sit under?",a:"Recover."}],
  r:[0,2],p:30},
 {t:"Frameworks as vocabulary",d:2,w:"Know ATT&CK tactic names and the OWASP Top 10 by heart. You will use both daily in a SOC.",
  q:[{q:"Name the ATT and CK tactics in order.",a:"Reconnaissance, Resource Development, Initial Access, Execution, Persistence, Privilege Escalation, Defense Evasion, Credential Access, Discovery, Lateral Movement, Collection, Command and Control, Exfiltration, Impact."},
     {q:"What is the OWASP Top 10 a list of?",a:"The ten most critical web application security risks. It is a risk list, not a standard."}],
  r:[2,3],p:30}
],
"M1.2":[
 {t:"Symmetric, asymmetric, hashing",d:2,w:"Know which algorithm fits which problem and why.",
  q:[{q:"Which is faster, symmetric or asymmetric?",a:"Symmetric, which is why TLS uses both."},
     {q:"Why can you not reverse a hash?",a:"It is a one-way function by design."}],
  r:[0],p:20},
 {t:"TLS handshake end to end",d:4,w:"Walk the handshake and explain every message. Do it by hand before reading a tool's output.",
  q:[{q:"What is the point of the certificate authority?",a:"It vouches that a public key belongs to who claims it owns it."},
     {q:"What is session key pinning?",a:"Restricting which keys the client will accept, limiting exposure to a rogue CA."}],
  r:[2],p:40},
 {t:"Read a certificate",d:3,w:"Open a real site's certificate, check the chain, the expiry and the SANs.",
  q:[{q:"Run a domain through SSL Labs and explain every downgrade you see.",a:"Any real answer from an actual test you ran."}],
  r:[3],p:30},
 {t:"Break the classics",d:4,w:"CryptoPals sets 1 and 2 by hand, no libraries. The point is seeing the maths.",
  q:[{q:"Why is ECB mode broken?",a:"Identical plaintext blocks produce identical ciphertext blocks, so patterns leak."},
     {q:"Why do you salt passwords?",a:"So identical passwords hash differently and a precomputed rainbow table is useless."}],
  r:[1],p:50}
],
"M1.3":[
 {t:"Build and harden a Linux box",d:2,w:"Install Ubuntu in a VM, then disable root SSH, install key-only auth and configure a firewall.",
  q:[{q:"What is the single most important SSH hardening step?",a:"Disable password authentication and use keys only."},
     {q:"Which command checks listening ports?",a:"ss -tulnp  (or netstat -tulnp)"}],
  r:[2],p:30},
 {t:"Windows fundamentals",d:2,w:"Services, local admin, RDP, and where Windows keeps its logs.",
  q:[{q:"Which log holds failed logon attempts on Windows?",a:"The Security log, event ID 4625."},
     {q:"Which event ID is a successful logon?",a:"4624."}],
  r:[0,1],p:30},
 {t:"Know your baseline",d:3,w:"This is the module that matters most for SOC work. Write down what normal looks like before hunting anomalies.",
  q:[{q:"Why can you not spot an anomaly without a baseline?",a:"An anomaly is defined as a deviation. Without knowing normal you have nothing to compare against."}],
  r:[3],p:40},
 {t:"Stand up a lab safely",d:3,w:"Build a deliberately vulnerable box on a host-only network. Never expose it to the internet.",
  q:[{q:"What network mode should a lab VM use?",a:"Host-only, so traffic cannot leave your machine."}],
  r:[2,3],p:40}
],
"M2.1":[
 {t:"Scoping and rules of engagement",d:1,w:"Unauthorised scanning is a crime. Authorised scanning is a job. The document is the difference.",
  q:[{q:"What does a rules of engagement document define?",a:"What you may test, when, how, and what happens if you break something."}],
  r:[4],p:20},
 {t:"Passive recon",d:2,w:"Gather everything from public sources before touching the target directly.",
  q:[{q:"What does certificate transparency give you?",a:"Every certificate issued for a domain, so you can discover subdomains without touching the target."}],
  r:[2,1],p:30},
 {t:"Active enumeration",d:3,w:"Port and service scanning against a target you own or are authorised to test.",
  q:[{q:"What is a default credential list useful for?",a:"Finding devices shipped with a known username and password."}],
  r:[1],p:30},
 {t:"Tech fingerprinting",d:3,w:"Identify frameworks, versions and exposed services, then record everything.",
  q:[{q:"Why do version numbers matter?",a:"They let you match a service to known CVEs without guessing."}],
  r:[3],p:40},
 {t:"Write the report",d:3,w:"Findings with severity and business impact, not just a tool dump.",
  q:[{q:"What makes a finding actionable?",a:"The business impact and a concrete fix, not just the technical description."}],
  r:[4,0],p:40}
],
"M2.2":[
 {t:"The request lifecycle",d:2,w:"Understand what happens from typing a URL to a response, and where each attack gets injected.",
  q:[{q:"What is SQL injection?",a:"User input reaching a query unescaped, so the attacker changes the query's meaning."},
     {q:"What is IDOR?",a:"Changing an object ID in a request to reach someone else's data, with no check on ownership."}],
  r:[4],p:30},
 {t:"PortSwigger apprentice labs",d:3,w:"Do these in order. Do not skip to the exploit, read every stage of the walkthrough.",
  q:[{q:"Complete at least 10 apprentice labs and write each one up.",a:"Anything, as long as the writeups exist."}],
  r:[0],p:50},
 {t:"Stand up Juice Shop",d:3,w:"Run it locally, then fix 15 of its findings and document each one.",
  q:[{q:"Why run a deliberately vulnerable app?",a:"So you can practise finding and fixing without risking a real system."}],
  r:[1],p:40},
 {t:"Broken access control",d:4,w:"The number one web flaw in practice. Test for BOLA and mass assignment on every API you touch.",
  q:[{q:"What is mass assignment?",a:"Binding user-supplied JSON straight to a model so the client can set privileged fields."}],
  r:[1,2],p:40},
 {t:"Read the framework docs",d:2,w:"OWASP cheat sheets are the reference you will keep open for years.",
  q:[{q:"Which cheat sheet do you consult for authorisation design?",a:"The Authorization Cheat Sheet."}],
  r:[3,4],p:30}
],
"M2.3":[
 {t:"Memory corruption concepts",d:4,w:"Buffer overflow, ret2libc and ASLR bypass explained in plain language, without writing shellcode yet.",
  q:[{q:"Why does ASLR make exploitation harder?",a:"The stack addresses move every run, so a hardcoded return address is wrong."}],
  r:[0],p:40},
 {t:"Metasploit in a lab",d:3,w:"Drive the framework inside your own vulnerable box and read every output line.",
  q:[{q:"What does an exploit module's check code tell you?",a:"Whether the target is actually vulnerable, before anything is sent."}],
  r:[0],p:40},
 {t:"Pivot through a network",d:4,w:"Build a two-segment lab and move between them using SSH or SOCKS tunnels.",
  q:[{q:"Why pivot at all?",a:"Because reaching one host gives you the credentials and network position to reach the next."}],
  r:[0],p:50},
 {t:"Practice on public targets",d:3,w:"VulnHub VMs and HTB Starting Point. Write the walkthrough while you solve, not after.",
  q:[{q:"Why write during the solve?",a:"You will not reconstruct the reasoning later, and the writeup is portfolio evidence."}],
  r:[2,3],p:50},
 {t:"Free CTF practice",d:2,w:"picoGym and CyLab give you repeatable crypto and pwn challenges at any difficulty.",
  q:[{q:"Pick a challenge below your level and solve it.",a:"Any answer, provided you actually did it."}],
  r:[1],p:30}
],
"M3.1":[
 {t:"What a SOC actually does",d:1,w:"Tiers, SLAs, escalation paths and shift handover. Understand the job before the tools.",
  q:[{q:"What is a SOC tier 1 analyst's main job?",a:"Triage: decide whether an alert is a true positive, then escalate or close it."},
     {q:"What is an SLA in this context?",a:"The agreed time within which an alert must be triaged or escalated."}],
  r:[2],p:20},
 {t:"Learn a SIEM",d:3,w:"Build one working detection in Splunk or Elastic from an empty search.",
  q:[{q:"What is the first thing you need before writing a detection?",a:"A data source and a known log field you can filter on."}],
  r:[3,4],p:40},
 {t:"Write KQL and hunt",d:4,w:"Query for real attacker techniques rather than generic anomalies.",
  q:[{q:"Which event IDs should you know by name?",a:"4624 successful logon, 4625 failed logon, 4688 process creation, 4648 explicit credential logon, 4104 PowerShell script block, 7045 service installed, 1149 authentication package loaded, and 21 to 25 for the System log."}],
  r:[5],p:50},
 {t:"Triage for real",d:4,w:"Take an alert from detection to decision, and write the writeup a manager could read.",
  q:[{q:"What belongs in an alert writeup?",a:"What triggered it, what the evidence shows, whether it is a true positive, the impact, and the recommended action."}],
  r:[0],p:50},
 {t:"Practise blue team",d:3,w:"Complete 15 CyberDefenders challenges. This is the closest free practice to the actual job.",
  q:[{q:"What does CyberDefenders simulate?",a:"Real SOC and DFIR scenarios with real log and memory evidence."}],
  r:[0,1],p:50}
],
"M3.2":[
 {t:"Kerberos, NTLM, LDAP",d:3,w:"Understand the three protocols that carry Windows authentication, and why each exists.",
  q:[{q:"Why does Kerberos use tickets?",a:"So the password never crosses the network, and the same ticket can be reused across services."},
     {q:"What is NTLM still used for?",a:"Legacy systems and older authentication paths. It remains everywhere in real estates."}],
  r:[1,2],p:40},
 {t:"Enumerate a domain",d:4,w:"Stand up a real AD domain and enumerate it the way an assessor would.",
  q:[{q:"Why enumerate users?",a:"Because accounts and group membership are the map of what is reachable and who can reach it."}],
  r:[0],p:50},
 {t:"Credential attacks explained",d:4,risk:true,w:"Understand kerberoasting, pass-the-hash and ticket forgery conceptually, and detect each one.",
  q:[{q:"What is kerberoasting?",a:"Requesting service tickets for accounts with weak passwords, then cracking them offline."},
     {q:"What does pass-the-hash rely on?",a:"Authentication protocols accepting a password hash directly as proof, which NTLM does."}],
  r:[1],p:50},
 {t:"Detect in the log",d:4,w:"For every event ID you learn, find it in a real log and justify the triage decision.",
  q:[{q:"A burst of 4625 then one 4624 for the same account, what is your call?",a:"Likely successful password guessing. Check the source address, then whether the successful logon is followed by anything unusual."}],
  r:[3,4],p:50},
 {t:"Hardening and baselines",d:3,w:"Know what a hardened domain looks like, and use the reference to check yours.",
  q:[{q:"Name one AD hardening baseline item.",a:"For example disabling NTLM, restricting privileged groups to domain admins only, or enforcing MFA on privileged access."}],
  r:[2],p:40}
],
"M3.3":[
 {t:"How firewalls decide",d:2,w:"Stateful inspection, rule order, and why the first match wins.",
  q:[{q:"What does stateful mean?",a:"The firewall tracks connections, not just packets, and allows reply traffic for traffic it already permitted."},
     {q:"Why does rule order matter?",a:"Rules are evaluated top down and the first match is applied, so a permissive rule above a strict one makes the strict one dead."}],
  r:[3],p:30},
 {t:"Deploy Suricata",d:3,w:"Write three rules, trigger them yourself, and explain each alert.",
  q:[{q:"Which tool validates a Suricata rule offline?",a:"suricata-verify"}],
  r:[0],p:40},
 {t:"Read IDS alerts",d:4,w:"Tell a false positive from a real one, and justify which you concluded.",
  q:[{q:"What makes a good Suricata rule?",a:"Specific enough to be low false positive, broad enough to catch variants."}],
  r:[1],p:40},
 {t:"Segment the network",d:3,w:"Split your lab into three zones and prove isolation with a scan.",
  q:[{q:"What does segmentation reduce?",a:"Blast radius. It limits how far an attacker can move after one host is compromised."}],
  r:[3,4],p:40},
 {t:"Monitor the wire",d:3,w:"Use Wireshark and Zeek to read traffic the way an investigator would.",
  q:[{q:"What does Zeek add over raw packet capture?",a:"Connection and protocol logs with parsed fields, which you can actually search."}],
  r:[1,2],p:40}
],
"M4.1":[
 {t:"Static triage first",d:2,w:"Hashes, strings, imports, packers. Never open a sample before you have triaged it.",
  q:[{q:"Why hash a sample before opening it?",a:"It gives you an identifier you can check against reputation feeds without executing anything."}],
  r:[1],p:30},
 {t:"Sandbox safely",d:3,w:"Analyse dynamically in an isolated sandbox and record the behaviour.",
  q:[{q:"What does a detonation sandbox give you that static does not?",a:"Observed runtime behaviour: network calls, registry writes, dropped files, process injection."}],
  r:[0],p:40},
 {t:"Extract indicators",d:3,w:"Every analysis ends with an IOC list somebody can act on.",
  q:[{q:"What belongs in an IOC list?",a:"Hashes, domains, IPs, URLs, file paths, registry keys and mutexes, each with context and first-seen time."}],
  r:[1,4],p:40},
 {t:"Read a beacon config",d:4,w:"Parse a Cobalt Strike configuration out of a PCAP and explain every field.",
  q:[{q:"Which beacon field tells you the sleep time?",a:"The sleep interval setting inside the decoded configuration block."}],
  r:[2,3],p:50},
 {t:"Write the report",d:3,w:"Produce something a detection engineer could turn into a rule.",
  q:[{q:"What makes malware analysis useful to a SOC?",a:"The indicator list and the behaviour description, both specific enough to alert on."}],
  r:[3],p:40}
],
"M4.2":[
 {t:"Shared responsibility",d:1,w:"Know exactly what the provider secures and what you are still accountable for.",
  q:[{q:"Who patches the hypervisor?",a:"The provider. Who patches your operating system?",a:"You, always."}],
  r:[1],p:20},
 {t:"IAM and least privilege",d:3,w:"Enumerate your own account for over-privileged roles.",
  q:[{q:"What is the most common cloud finding?",a:"Over-permissive IAM roles, far more often than a provider misconfiguration."}],
  r:[0,1],p:40},
 {t:"Expose it, then fix it",d:4,w:"Make a bucket public, prove it, then lock it down and re-scan to prove the fix stuck.",
  q:[{q:"Why re-scan after fixing?",a:"Because a fix that was not verified is a fix you cannot claim to have made."}],
  r:[2],p:50},
 {t:"Cloud logging",d:3,w:"Set up the audit logs you would actually use for detection.",
  q:[{q:"Which cloud log answers who deleted the bucket?",a:"The audit or activity log, read through CloudTrail or Azure Monitor."}],
  r:[1,2],p:40},
 {t:"IaC and automation",d:3,w:"Understand why insecure infrastructure code is a supply chain problem.",
  q:[{q:"Why scan infrastructure code?",a:"Because a public storage block in Terraform ships a public bucket on the next apply."}],
  r:[4],p:40}
],
"M4.3":[
 {t:"Pick one program",d:2,w:"Go deep on a single in-scope program rather than five shallow ones.",
  q:[{q:"What makes a report triaged rather than ignored?",a:"Clear reproduction steps, real impact, and a specific fix."}],
  r:[0,1],p:30},
 {t:"Report a real bug",d:4,risk:true,w:"Submit an in-scope report and get it triaged. Respect the rules of engagement at all times.",
  q:[{q:"What must every report state?",a:"Scope, the vulnerability, step by step reproduction, impact, and remediation."}],
  r:[0,1],p:50},
 {t:"Write it up publicly",d:3,w:"Publish the writeup once the program allows it. This is the trail bounty income depends on.",
  q:[{q:"Why write up bounty reports publicly?",a:"It proves the skill to recruiters and clients, and it is the only durable evidence of the work."}],
  r:[2,3],p:40},
 {t:"Sustain the streak",d:2,w:"Hold a weekly lab or CTF streak for three months.",
  q:[{q:"What is the point of a streak?",a:"It proves consistency, which is the thing employers doubt about self-taught candidates."}],
  r:[2],p:30},
 {t:"Practise the wider range",d:3,w:"Use free platforms to keep sharp outside your primary target type.",
  q:[{q:"Why practise on CTFs when you do real bug bounty?",a:"CTFs let you try destructive techniques you would never attempt on a live in-scope target."}],
  r:[4,5],p:40}
],
"M5.1":[
 {t:"Choose exactly one cert",d:2,w:"One exam, passed. Four half attempts look far worse than one finish.",
  q:[{q:"Which cert do PH SOC job ads filter on most?",a:"CompTIA Security+ most often, with SC-900 appearing in Microsoft-aligned and government roles."},
     {q:"Should you do Network+ if you do CCNA?",a:"No. Forums consider it redundant. Pick one path."}],
  r:[0],p:30},
 {t:"Free study material",d:1,w:"Messer covers the whole Security+ syllabus free. Finish it before booking anything.",
  q:[{q:"Is the Security+ exam worth taking while a student?",a:"Only if employers in your target list filter on it. Free vendor credentials often carry more weight locally first."}],
  r:[0],p:20},
 {t:"Microsoft credentials",d:2,w:"The SC-900 study guide is free. The exam is not.",
  q:[{q:"What does SC-900 cover?",a:"Security, compliance and identity fundamentals, including Defender, Entra, Purview and the shared responsibility model."}],
  r:[1,2],p:30},
 {t:"Write the resume",d:3,w:"One page, leading with proof rather than a certificate list.",
  q:[{q:"What should the first line under your name say?",a:"What you can do and want to do, not what courses you have finished."},
     {q:"How many tools should you list?",a:"Only ones you could be asked about. Five well explained beats twenty named."}],
  r:[3],p:40},
 {t:"Apply and interview",d:3,w:"Thirty applications a week, and eight recorded mock interviews before you are ready.",
  q:[{q:"What must you be able to do for a SOC interview?",a:"Read a log out loud, explain what is suspicious about it, and justify your triage decision."}],
  r:[3],p:40}
],
"M5.2":[
 {t:"Every repo needs a README",d:2,w:"Threat, detection, proof of concept, result. Four headings, on all twelve tools.",
  q:[{q:"What is the first section of a security tool README?",a:"The threat it addresses or detects."}],
  r:[0,3],p:30},
 {t:"Make the site legible",d:2,w:"Each project needs a screenshot and a one line impact statement.",
  q:[{q:"How long should a recruiter take to understand your work?",a:"Thirty seconds on the landing page, then one click per project."}],
  r:[1],p:30},
 {t:"Public proof of practice",d:3,w:"Ten or more lab writeups published publicly.",
  q:[{q:"What does a CTF writeup prove that a certificate cannot?",a:"That you can solve problems under pressure and explain your reasoning."}],
  r:[2],p:40},
 {t:"Host it free",d:1,w:"Keep everything on GitHub Pages so a recruiter can always reach it.",
  q:[{q:"Why does a live demo matter more than a screenshot?",a:"A screenshot can be faked. A running tool cannot."}],
  r:[4],p:20},
 {t:"Get found",d:2,w:"Set up a CyberDefenders profile so your practice is publicly verifiable.",
  q:[{q:"What does a public CTF profile signal to a hiring manager?",a:"Consistent practice, verified by someone other than you."}],
  r:[2],p:30}
]
};
window.TASKS=TASKS;